package app.echo.android.feature.settings

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import app.echo.android.model.playback.EchoPlaybackStatus
import app.echo.android.model.playback.EchoReplayGainMode
import app.echo.android.model.settings.EchoBackgroundStyle
import app.echo.android.model.settings.EchoEffectivePerformanceMode

@Composable
fun SettingsScreen(
    isActive: Boolean = true,
    importedFontFamily: FontFamily? = null,
    status: EchoPlaybackStatus,
    trackCount: Int,
    albumCount: Int,
    artistCount: Int,
    libraryDurationMs: Long = 0L,
    librarySizeBytes: Long = 0L,
    libraryScanning: Boolean = false,
    onLoadLibraryHealth: suspend () -> app.echo.android.model.library.LibraryHealthStats = {
        app.echo.android.model.library.LibraryHealthStats()
    },
    onInspectLibraryLyrics: suspend ((app.echo.android.model.library.LibraryLyricsInspection) -> Unit) -> Unit = {},
    appVersionLabel: String,
    updateContent: @Composable () -> Unit = {},
    dynamicArtworkEnabled: Boolean,
    compactModeEnabled: Boolean,
    playbackHapticsEnabled: Boolean,
    performanceMode: String,
    effectivePerformanceMode: String,
    trackAudioInfoTagsVisible: Boolean,
    watchedFolderRescanEnabled: Boolean,
    offlineWifiOnly: Boolean = true,
    offlineUsedBytes: Long = 0L,
    pcHandoffEnabled: Boolean,
    onlineLyricsEnabled: Boolean,
    lockScreenLyricsEnabled: Boolean,
    floatingLyrics: app.echo.android.model.settings.EchoFloatingLyricsSettings =
        app.echo.android.model.settings.EchoFloatingLyricsSettings(),
    floatingLyricsPermissionGranted: Boolean = false,
    lyricsOptions: app.echo.android.model.settings.EchoLyricsOptions = app.echo.android.model.settings.EchoLyricsOptions(),
    onLyricsOptionsChange: (app.echo.android.model.settings.EchoLyricsOptions) -> Unit = {},
    onOpenLyricsInterface: () -> Unit = {},
    usbExclusiveEnabled: Boolean,
    usbBitPerfectEnabled: Boolean,
    trackTransitions: app.echo.android.model.playback.EchoTrackTransitionOptions,
    usbExclusiveAutoRequestOnStartup: Boolean,
    pauseOnAudioDisconnect: Boolean,
    resumeOnAudioReconnect: Boolean,
    replayGainEnabled: Boolean,
    replayGainMode: String,
    replayGainPreampDb: Float,
    usbExclusiveTestResult: String,
    customBackgroundMode: String,
    customBackgroundUri: String?,
    startupBackgroundUri: String?,
    customBackgroundBlur: Float,
    customBackgroundBrightness: Float,
    customBackgroundGlass: Float,
    customBackgroundScale: Float,
    uiFontFamily: String,
    uiFontScale: Float,
    uiDensityScale: Float,
    lyricsFontFamily: String,
    lyricsFontScale: Float,
    importedFontUri: String?,
    themeMode: String,
    appLanguage: String,
    scheduledDarkModeEnabled: Boolean,
    scheduledDarkStartMinute: Int,
    scheduledDarkEndMinute: Int,
    lastFmEnabled: Boolean,
    lastFmApiKey: String?,
    lastFmSharedSecret: String?,
    lastFmSessionKey: String?,
    lastFmStatusLabel: String,
    lastFmErrorLabel: String?,
    lastFmWebAuthPending: Boolean,
    lastFmApiKeyLocked: Boolean,
    lastFmSharedSecretLocked: Boolean,
    listenBrainzEnabled: Boolean,
    listenBrainzToken: String?,
    listenBrainzStatusLabel: String,
    listenBrainzErrorLabel: String?,
    setlistFmApiKey: String? = null,
    setlistFmApiKeyLocked: Boolean = false,
    onDynamicArtworkEnabledChange: (Boolean) -> Unit,
    onCompactModeEnabledChange: (Boolean) -> Unit,
    onPlaybackHapticsEnabledChange: (Boolean) -> Unit,
    onPerformanceModeChange: (String) -> Unit,
    onTrackAudioInfoTagsVisibleChange: (Boolean) -> Unit,
    onWatchedFolderRescanEnabledChange: (Boolean) -> Unit,
    onOfflineWifiOnlyChange: (Boolean) -> Unit = {},
    onPcHandoffEnabledChange: (Boolean) -> Unit,
    onOnlineLyricsEnabledChange: (Boolean) -> Unit,
    onLockScreenLyricsEnabledChange: (Boolean) -> Unit,
    onFloatingLyricsChange: (app.echo.android.model.settings.EchoFloatingLyricsSettings) -> Unit = {},
    onRequestFloatingLyricsPermission: () -> Unit = {},
    onUsbExclusiveEnabledChange: (Boolean) -> Unit,
    onUsbBitPerfectEnabledChange: (Boolean) -> Unit,
    onTrackTransitionsChange: (app.echo.android.model.playback.EchoTrackTransitionOptions) -> Unit,
    onUsbExclusiveAutoRequestOnStartupChange: (Boolean) -> Unit,
    onPauseOnAudioDisconnectChange: (Boolean) -> Unit,
    onResumeOnAudioReconnectChange: (Boolean) -> Unit,
    onReplayGainChange: (Boolean, Float) -> Unit,
    onReplayGainModeChange: (EchoReplayGainMode) -> Unit,
    onTestUsbExclusiveDriver: () -> Unit,
    onPickImageBackground: () -> Unit,
    onPickStartupBackground: () -> Unit,
    onClearStartupBackground: () -> Unit,
    onPickVideoBackground: () -> Unit,
    onClearCustomBackground: () -> Unit,
    onCustomBackgroundBlurChange: (Float) -> Unit,
    onCustomBackgroundBrightnessChange: (Float) -> Unit,
    onCustomBackgroundGlassChange: (Float) -> Unit,
    onCustomBackgroundScaleChange: (Float) -> Unit,
    onCustomBackgroundStyleChange: (EchoBackgroundStyle) -> Unit,
    onUiFontFamilyChange: (String) -> Unit,
    onUiFontScaleChange: (Float) -> Unit,
    onUiDensityScaleChange: (Float) -> Unit,
    onLyricsFontFamilyChange: (String) -> Unit,
    onLyricsFontScaleChange: (Float) -> Unit,
    onImportUiFont: () -> Unit,
    onImportLyricsFont: () -> Unit,
    onClearImportedFont: () -> Unit,
    onThemeModeChange: (String) -> Unit,
    onAppLanguageChange: (String) -> Unit,
    onScheduledDarkModeEnabledChange: (Boolean) -> Unit,
    onScheduledDarkStartMinuteChange: (Int) -> Unit,
    onScheduledDarkEndMinuteChange: (Int) -> Unit,
    onLastFmEnabledChange: (Boolean) -> Unit,
    onStartLastFmWebAuth: () -> Unit,
    onCompleteLastFmWebAuth: () -> Unit,
    onDisconnectLastFm: () -> Unit,
    onOpenLastFmApiAccounts: () -> Unit,
    onListenBrainzEnabledChange: (Boolean) -> Unit,
    onSaveListenBrainzToken: (String) -> Unit,
    onDisconnectListenBrainz: () -> Unit,
    onSaveSetlistFmApiKey: (String?) -> Unit = {},
    onOpenLibrary: () -> Unit,
    onClearLocalLibraryIndex: suspend () -> Boolean,
    onCleanupLocalLibrary: suspend () -> Pair<Int, Int> = { 0 to 0 },
    errorLogCount: Int = 0,
    onOpenErrorLog: () -> Unit = {},
    backupNotice: app.echo.android.model.backup.EchoBackupNotice? = null,
    onExportBackup: () -> Unit = {},
    onImportBackup: () -> Unit = {},
    notificationPermissionGranted: Boolean = true,
    onRequestNotificationPermission: () -> Unit = {},
    onOpenPlugins: () -> Unit = {},
    isPageVisible: Boolean = isActive,
) {
    SettingsNavigation(
        isActive = isActive,
        isPageVisible = isPageVisible,
        compactMode = compactModeEnabled,
        onOpenPlugins = onOpenPlugins,
        searchAvailability = SettingsSearchAvailability(
            scheduledDarkEnabled = scheduledDarkModeEnabled,
            customBackgroundMode = customBackgroundMode,
            backgroundAdvancedAvailable = customBackgroundMode != "default" &&
                !customBackgroundUri.isNullOrBlank() &&
                !(customBackgroundMode == "video" &&
                    effectivePerformanceMode == EchoEffectivePerformanceMode.Lightweight.id),
            trackFadeEnabled = trackTransitions.fadeEnabled,
            replayGainEnabled = replayGainEnabled,
            lastFmEnabled = lastFmEnabled,
            lastFmConnected = lastFmEnabled && !lastFmSessionKey.isNullOrBlank(),
            listenBrainzEnabled = listenBrainzEnabled,
            listenBrainzConnected = listenBrainzEnabled && !listenBrainzToken.isNullOrBlank(),
            setlistFmLocked = setlistFmApiKeyLocked,
            importedFont = !importedFontUri.isNullOrBlank(),
            notificationPermissionNeeded = app.echo.android.design.LocalEchoPlatformCapabilities.current
                .notificationRuntimePermission && !notificationPermissionGranted,
            usbConfigurationVisible = status.diagnostics.usbConnected || usbExclusiveEnabled || usbBitPerfectEnabled ||
                usbExclusiveAutoRequestOnStartup,
        ),
        summaries = mapOf(
            SettingsCategory.Appearance to (stringResource(when (themeMode) {
                "dark" -> R.string.settings_theme_dark
                "light" -> R.string.settings_theme_light
                else -> R.string.settings_theme_system
            }) + " · " + stringResource(when (customBackgroundMode) {
                "image" -> R.string.settings_summary_bg_image
                "video" -> R.string.settings_summary_bg_video
                else -> R.string.settings_summary_bg_default
            })),
            SettingsCategory.Interface to languageDetail(appLanguage),
            SettingsCategory.Playback to stringResource(if (usbExclusiveEnabled) R.string.settings_usb_exclusive else R.string.settings_section_lyrics),
            SettingsCategory.Services to (lastFmStatusLabel + " · " + listenBrainzStatusLabel),
            SettingsCategory.Library to stringResource(R.string.settings_library_summary, trackCount, albumCount, artistCount),
            SettingsCategory.About to appVersionLabel,
        ),
    ) { category ->
        when (category) {
                SettingsCategory.Appearance -> SettingsAppearanceContent(
                    importedFontFamily = importedFontFamily,
                    customBackgroundMode = customBackgroundMode,
                    customBackgroundUri = customBackgroundUri,
                    startupBackgroundUri = startupBackgroundUri,
                    customBackgroundBlur = customBackgroundBlur,
                    customBackgroundBrightness = customBackgroundBrightness,
                    customBackgroundGlass = customBackgroundGlass,
                    customBackgroundScale = customBackgroundScale,
                    uiFontFamily = uiFontFamily,
                    uiFontScale = uiFontScale,
                    uiDensityScale = uiDensityScale,
                    lyricsFontFamily = lyricsFontFamily,
                    lyricsFontScale = lyricsFontScale,
                    importedFontUri = importedFontUri,
                    themeMode = themeMode,
                    scheduledDarkModeEnabled = scheduledDarkModeEnabled,
                    scheduledDarkStartMinute = scheduledDarkStartMinute,
                    scheduledDarkEndMinute = scheduledDarkEndMinute,
                    onPickImageBackground = onPickImageBackground,
                    onPickStartupBackground = onPickStartupBackground,
                    onClearStartupBackground = onClearStartupBackground,
                    onPickVideoBackground = onPickVideoBackground,
                    onClearCustomBackground = onClearCustomBackground,
                    onCustomBackgroundBlurChange = onCustomBackgroundBlurChange,
                    onCustomBackgroundBrightnessChange = onCustomBackgroundBrightnessChange,
                    onCustomBackgroundGlassChange = onCustomBackgroundGlassChange,
                    onCustomBackgroundScaleChange = onCustomBackgroundScaleChange,
                    onCustomBackgroundStyleChange = onCustomBackgroundStyleChange,
                    onUiFontFamilyChange = onUiFontFamilyChange,
                    onUiFontScaleChange = onUiFontScaleChange,
                    onLyricsFontFamilyChange = onLyricsFontFamilyChange,
                    onLyricsFontScaleChange = onLyricsFontScaleChange,
                    onImportUiFont = onImportUiFont,
                    onImportLyricsFont = onImportLyricsFont,
                    onClearImportedFont = onClearImportedFont,
                    onThemeModeChange = onThemeModeChange,
                    onScheduledDarkModeEnabledChange = onScheduledDarkModeEnabledChange,
                    onScheduledDarkStartMinuteChange = onScheduledDarkStartMinuteChange,
                    onScheduledDarkEndMinuteChange = onScheduledDarkEndMinuteChange,
                )
                SettingsCategory.Interface -> SettingsInterfaceContent(
                    dynamicArtworkEnabled = dynamicArtworkEnabled,
                    compactModeEnabled = compactModeEnabled,
                    uiDensityScale = uiDensityScale,
                    performanceMode = performanceMode,
                    effectivePerformanceMode = effectivePerformanceMode,
                    appLanguage = appLanguage,
                    onDynamicArtworkEnabledChange = onDynamicArtworkEnabledChange,
                    onCompactModeEnabledChange = onCompactModeEnabledChange,
                    onUiDensityScaleChange = onUiDensityScaleChange,
                    onPerformanceModeChange = onPerformanceModeChange,
                    onAppLanguageChange = onAppLanguageChange,
                )
                SettingsCategory.Playback -> SettingsPlaybackContent(
                    status = status,
                    playbackHapticsEnabled = playbackHapticsEnabled,
                    effectivePerformanceMode = effectivePerformanceMode,
                    onlineLyricsEnabled = onlineLyricsEnabled,
                    lockScreenLyricsEnabled = lockScreenLyricsEnabled,
                    lyricsOptions = lyricsOptions,
                    onLyricsOptionsChange = onLyricsOptionsChange,
                    onOpenLyricsInterface = onOpenLyricsInterface,
                    floatingLyrics = floatingLyrics,
                    floatingLyricsPermissionGranted = floatingLyricsPermissionGranted,
                    usbExclusiveEnabled = usbExclusiveEnabled,
                    usbBitPerfectEnabled = usbBitPerfectEnabled,
                    trackTransitions = trackTransitions,
                    usbExclusiveAutoRequestOnStartup = usbExclusiveAutoRequestOnStartup,
                    pauseOnAudioDisconnect = pauseOnAudioDisconnect,
                    resumeOnAudioReconnect = resumeOnAudioReconnect,
                    replayGainEnabled = replayGainEnabled,
                    replayGainMode = replayGainMode,
                    replayGainPreampDb = replayGainPreampDb,
                    usbExclusiveTestResult = usbExclusiveTestResult,
                    onPlaybackHapticsEnabledChange = onPlaybackHapticsEnabledChange,
                    onOnlineLyricsEnabledChange = onOnlineLyricsEnabledChange,
                    onLockScreenLyricsEnabledChange = onLockScreenLyricsEnabledChange,
                    onFloatingLyricsChange = onFloatingLyricsChange,
                    onRequestFloatingLyricsPermission = onRequestFloatingLyricsPermission,
                    onUsbExclusiveEnabledChange = onUsbExclusiveEnabledChange,
                    onUsbBitPerfectEnabledChange = onUsbBitPerfectEnabledChange,
                    onTrackTransitionsChange = onTrackTransitionsChange,
                    onUsbExclusiveAutoRequestOnStartupChange = onUsbExclusiveAutoRequestOnStartupChange,
                    onPauseOnAudioDisconnectChange = onPauseOnAudioDisconnectChange,
                    onResumeOnAudioReconnectChange = onResumeOnAudioReconnectChange,
                    onReplayGainChange = onReplayGainChange,
                    onReplayGainModeChange = onReplayGainModeChange,
                    onTestUsbExclusiveDriver = onTestUsbExclusiveDriver,
                    notificationPermissionGranted = notificationPermissionGranted,
                    onRequestNotificationPermission = onRequestNotificationPermission,
                )
                SettingsCategory.Services -> SettingsServicesContent(
                    pcHandoffEnabled = pcHandoffEnabled,
                    lastFmEnabled = lastFmEnabled,
                    lastFmApiKey = lastFmApiKey,
                    lastFmSharedSecret = lastFmSharedSecret,
                    lastFmSessionKey = lastFmSessionKey,
                    lastFmStatusLabel = lastFmStatusLabel,
                    lastFmErrorLabel = lastFmErrorLabel,
                    lastFmWebAuthPending = lastFmWebAuthPending,
                    lastFmApiKeyLocked = lastFmApiKeyLocked,
                    lastFmSharedSecretLocked = lastFmSharedSecretLocked,
                    listenBrainzEnabled = listenBrainzEnabled,
                    listenBrainzToken = listenBrainzToken,
                    listenBrainzStatusLabel = listenBrainzStatusLabel,
                    listenBrainzErrorLabel = listenBrainzErrorLabel,
                    setlistFmApiKey = setlistFmApiKey,
                    setlistFmApiKeyLocked = setlistFmApiKeyLocked,
                    onPcHandoffEnabledChange = onPcHandoffEnabledChange,
                    onLastFmEnabledChange = onLastFmEnabledChange,
                    onStartLastFmWebAuth = onStartLastFmWebAuth,
                    onCompleteLastFmWebAuth = onCompleteLastFmWebAuth,
                    onDisconnectLastFm = onDisconnectLastFm,
                    onOpenLastFmApiAccounts = onOpenLastFmApiAccounts,
                    onListenBrainzEnabledChange = onListenBrainzEnabledChange,
                    onSaveListenBrainzToken = onSaveListenBrainzToken,
                    onDisconnectListenBrainz = onDisconnectListenBrainz,
                    onSaveSetlistFmApiKey = onSaveSetlistFmApiKey,
                )
                SettingsCategory.Library -> SettingsLibraryContent(
                    isActive = isActive,
                    isScanning = libraryScanning,
                    onLoadHealth = onLoadLibraryHealth,
                    onInspectLyrics = onInspectLibraryLyrics,
                    trackCount = trackCount,
                    albumCount = albumCount,
                    artistCount = artistCount,
                    durationMs = libraryDurationMs,
                    localSizeBytes = librarySizeBytes,
                    trackAudioInfoTagsVisible = trackAudioInfoTagsVisible,
                    watchedFolderRescanEnabled = watchedFolderRescanEnabled,
                    offlineWifiOnly = offlineWifiOnly,
                    offlineUsedBytes = offlineUsedBytes,
                    onTrackAudioInfoTagsVisibleChange = onTrackAudioInfoTagsVisibleChange,
                    onWatchedFolderRescanEnabledChange = onWatchedFolderRescanEnabledChange,
                    onOfflineWifiOnlyChange = onOfflineWifiOnlyChange,
                    onOpenLibrary = onOpenLibrary,
                    onClearLocalLibraryIndex = onClearLocalLibraryIndex,
                    onCleanupLocalLibrary = onCleanupLocalLibrary,
                )
                SettingsCategory.About -> SettingsAboutContent(
                    appVersionLabel = appVersionLabel,
                    updateContent = updateContent,
                    errorLogCount = errorLogCount,
                    onOpenErrorLog = onOpenErrorLog,
                    backupNotice = backupNotice,
                    onExportBackup = onExportBackup,
                    onImportBackup = onImportBackup,
                )
        }
    }
}
