package app.echo.android.feature.settings

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import app.echo.android.model.playback.EchoPlaybackStatus
import app.echo.android.model.settings.EchoBackgroundStyle

@Composable
fun SettingsScreen(
    isActive: Boolean = true,
    status: EchoPlaybackStatus,
    trackCount: Int,
    albumCount: Int,
    artistCount: Int,
    appVersionLabel: String,
    dynamicArtworkEnabled: Boolean,
    compactModeEnabled: Boolean,
    dynamicColorEnabled: Boolean,
    playbackHapticsEnabled: Boolean,
    performanceMode: String,
    effectivePerformanceMode: String,
    trackAudioInfoTagsVisible: Boolean,
    pcHandoffEnabled: Boolean,
    showLyricsControlDeck: Boolean,
    onlineLyricsEnabled: Boolean,
    usbExclusiveEnabled: Boolean,
    usbBitPerfectEnabled: Boolean,
    trackTransitions: app.echo.android.model.playback.EchoTrackTransitionOptions,
    usbExclusiveAutoRequestOnStartup: Boolean,
    usbExclusiveTestResult: String,
    customBackgroundMode: String,
    customBackgroundUri: String?,
    customBackgroundBlur: Float,
    customBackgroundBrightness: Float,
    customBackgroundGlass: Float,
    customBackgroundScale: Float,
    uiFontFamily: String,
    uiFontScale: Float,
    uiDensityScale: Float,
    lyricsFontFamily: String,
    lyricsFontScale: Float,
    importedFontUri: String?,
    themeMode: String,
    appLanguage: String,
    scheduledDarkModeEnabled: Boolean,
    scheduledDarkStartMinute: Int,
    scheduledDarkEndMinute: Int,
    lastFmEnabled: Boolean,
    lastFmApiKey: String?,
    lastFmSharedSecret: String?,
    lastFmSessionKey: String?,
    lastFmStatusLabel: String,
    lastFmErrorLabel: String?,
    lastFmWebAuthPending: Boolean,
    lastFmApiKeyLocked: Boolean,
    lastFmSharedSecretLocked: Boolean,
    listenBrainzEnabled: Boolean,
    listenBrainzToken: String?,
    listenBrainzStatusLabel: String,
    listenBrainzErrorLabel: String?,
    onDynamicArtworkEnabledChange: (Boolean) -> Unit,
    onCompactModeEnabledChange: (Boolean) -> Unit,
    onDynamicColorEnabledChange: (Boolean) -> Unit,
    onPlaybackHapticsEnabledChange: (Boolean) -> Unit,
    onPerformanceModeChange: (String) -> Unit,
    onTrackAudioInfoTagsVisibleChange: (Boolean) -> Unit,
    onPcHandoffEnabledChange: (Boolean) -> Unit,
    onShowLyricsControlDeckChange: (Boolean) -> Unit,
    onOnlineLyricsEnabledChange: (Boolean) -> Unit,
    onUsbExclusiveEnabledChange: (Boolean) -> Unit,
    onUsbBitPerfectEnabledChange: (Boolean) -> Unit,
    onTrackTransitionsChange: (app.echo.android.model.playback.EchoTrackTransitionOptions) -> Unit,
    onUsbExclusiveAutoRequestOnStartupChange: (Boolean) -> Unit,
    onTestUsbExclusiveDriver: () -> Unit,
    onPickImageBackground: () -> Unit,
    onPickVideoBackground: () -> Unit,
    onClearCustomBackground: () -> Unit,
    onCustomBackgroundBlurChange: (Float) -> Unit,
    onCustomBackgroundBrightnessChange: (Float) -> Unit,
    onCustomBackgroundGlassChange: (Float) -> Unit,
    onCustomBackgroundScaleChange: (Float) -> Unit,
    onCustomBackgroundStyleChange: (EchoBackgroundStyle) -> Unit,
    onUiFontFamilyChange: (String) -> Unit,
    onUiFontScaleChange: (Float) -> Unit,
    onUiDensityScaleChange: (Float) -> Unit,
    onLyricsFontFamilyChange: (String) -> Unit,
    onLyricsFontScaleChange: (Float) -> Unit,
    onImportUiFont: () -> Unit,
    onImportLyricsFont: () -> Unit,
    onClearImportedFont: () -> Unit,
    onThemeModeChange: (String) -> Unit,
    onAppLanguageChange: (String) -> Unit,
    onScheduledDarkModeEnabledChange: (Boolean) -> Unit,
    onScheduledDarkStartMinuteChange: (Int) -> Unit,
    onScheduledDarkEndMinuteChange: (Int) -> Unit,
    onLastFmEnabledChange: (Boolean) -> Unit,
    onStartLastFmWebAuth: () -> Unit,
    onCompleteLastFmWebAuth: () -> Unit,
    onDisconnectLastFm: () -> Unit,
    onOpenLastFmApiAccounts: () -> Unit,
    onListenBrainzEnabledChange: (Boolean) -> Unit,
    onSaveListenBrainzToken: (String) -> Unit,
    onDisconnectListenBrainz: () -> Unit,
    onOpenLibrary: () -> Unit,
    onOpenConnect: () -> Unit,
    errorLogCount: Int = 0,
    onOpenErrorLog: () -> Unit = {},
    notificationPermissionGranted: Boolean = true,
    onRequestNotificationPermission: () -> Unit = {},
) {
    SettingsNavigation(
        isActive = isActive,
        compactMode = compactModeEnabled,
        summaries = mapOf(
            SettingsCategory.Appearance to (stringResource(when (themeMode) {
                "dark" -> R.string.settings_theme_dark
                "light" -> R.string.settings_theme_light
                else -> R.string.settings_theme_system
            }) + " · " + backgroundDetail(customBackgroundMode, customBackgroundUri)),
            SettingsCategory.Interface to (languageDetail(appLanguage) + " · " +
                performanceModeOptions().firstOrNull { it.value == performanceMode }?.label.orEmpty()),
            SettingsCategory.Playback to stringResource(if (usbExclusiveEnabled) R.string.settings_usb_exclusive else R.string.settings_gapless),
            SettingsCategory.Services to (lastFmStatusLabel + " · " + listenBrainzStatusLabel),
            SettingsCategory.Library to stringResource(R.string.settings_library_summary, trackCount, albumCount, artistCount),
            SettingsCategory.About to appVersionLabel,
        ),
    ) { category ->
        when (category) {
                SettingsCategory.Appearance -> SettingsAppearanceContent(
                    dynamicColorEnabled = dynamicColorEnabled,
                    customBackgroundMode = customBackgroundMode,
                    customBackgroundUri = customBackgroundUri,
                    customBackgroundBlur = customBackgroundBlur,
                    customBackgroundBrightness = customBackgroundBrightness,
                    customBackgroundGlass = customBackgroundGlass,
                    customBackgroundScale = customBackgroundScale,
                    uiFontFamily = uiFontFamily,
                    uiFontScale = uiFontScale,
                    uiDensityScale = uiDensityScale,
                    lyricsFontFamily = lyricsFontFamily,
                    lyricsFontScale = lyricsFontScale,
                    importedFontUri = importedFontUri,
                    themeMode = themeMode,
                    scheduledDarkModeEnabled = scheduledDarkModeEnabled,
                    scheduledDarkStartMinute = scheduledDarkStartMinute,
                    scheduledDarkEndMinute = scheduledDarkEndMinute,
                    onDynamicColorEnabledChange = onDynamicColorEnabledChange,
                    onPickImageBackground = onPickImageBackground,
                    onPickVideoBackground = onPickVideoBackground,
                    onClearCustomBackground = onClearCustomBackground,
                    onCustomBackgroundBlurChange = onCustomBackgroundBlurChange,
                    onCustomBackgroundBrightnessChange = onCustomBackgroundBrightnessChange,
                    onCustomBackgroundGlassChange = onCustomBackgroundGlassChange,
                    onCustomBackgroundScaleChange = onCustomBackgroundScaleChange,
                    onCustomBackgroundStyleChange = onCustomBackgroundStyleChange,
                    onUiFontFamilyChange = onUiFontFamilyChange,
                    onUiFontScaleChange = onUiFontScaleChange,
                    onUiDensityScaleChange = onUiDensityScaleChange,
                    onLyricsFontFamilyChange = onLyricsFontFamilyChange,
                    onLyricsFontScaleChange = onLyricsFontScaleChange,
                    onImportUiFont = onImportUiFont,
                    onImportLyricsFont = onImportLyricsFont,
                    onClearImportedFont = onClearImportedFont,
                    onThemeModeChange = onThemeModeChange,
                    onScheduledDarkModeEnabledChange = onScheduledDarkModeEnabledChange,
                    onScheduledDarkStartMinuteChange = onScheduledDarkStartMinuteChange,
                    onScheduledDarkEndMinuteChange = onScheduledDarkEndMinuteChange,
                )
                SettingsCategory.Interface -> SettingsInterfaceContent(
                    dynamicArtworkEnabled = dynamicArtworkEnabled,
                    compactModeEnabled = compactModeEnabled,
                    performanceMode = performanceMode,
                    effectivePerformanceMode = effectivePerformanceMode,
                    appLanguage = appLanguage,
                    onDynamicArtworkEnabledChange = onDynamicArtworkEnabledChange,
                    onCompactModeEnabledChange = onCompactModeEnabledChange,
                    onPerformanceModeChange = onPerformanceModeChange,
                    onAppLanguageChange = onAppLanguageChange,
                )
                SettingsCategory.Playback -> SettingsPlaybackContent(
                    status = status,
                    playbackHapticsEnabled = playbackHapticsEnabled,
                    effectivePerformanceMode = effectivePerformanceMode,
                    showLyricsControlDeck = showLyricsControlDeck,
                    onlineLyricsEnabled = onlineLyricsEnabled,
                    usbExclusiveEnabled = usbExclusiveEnabled,
                    usbBitPerfectEnabled = usbBitPerfectEnabled,
                    trackTransitions = trackTransitions,
                    usbExclusiveAutoRequestOnStartup = usbExclusiveAutoRequestOnStartup,
                    usbExclusiveTestResult = usbExclusiveTestResult,
                    onPlaybackHapticsEnabledChange = onPlaybackHapticsEnabledChange,
                    onShowLyricsControlDeckChange = onShowLyricsControlDeckChange,
                    onOnlineLyricsEnabledChange = onOnlineLyricsEnabledChange,
                    onUsbExclusiveEnabledChange = onUsbExclusiveEnabledChange,
                    onUsbBitPerfectEnabledChange = onUsbBitPerfectEnabledChange,
                    onTrackTransitionsChange = onTrackTransitionsChange,
                    onUsbExclusiveAutoRequestOnStartupChange = onUsbExclusiveAutoRequestOnStartupChange,
                    onTestUsbExclusiveDriver = onTestUsbExclusiveDriver,
                    notificationPermissionGranted = notificationPermissionGranted,
                    onRequestNotificationPermission = onRequestNotificationPermission,
                )
                SettingsCategory.Services -> SettingsServicesContent(
                    pcHandoffEnabled = pcHandoffEnabled,
                    lastFmEnabled = lastFmEnabled,
                    lastFmApiKey = lastFmApiKey,
                    lastFmSharedSecret = lastFmSharedSecret,
                    lastFmSessionKey = lastFmSessionKey,
                    lastFmStatusLabel = lastFmStatusLabel,
                    lastFmErrorLabel = lastFmErrorLabel,
                    lastFmWebAuthPending = lastFmWebAuthPending,
                    lastFmApiKeyLocked = lastFmApiKeyLocked,
                    lastFmSharedSecretLocked = lastFmSharedSecretLocked,
                    listenBrainzEnabled = listenBrainzEnabled,
                    listenBrainzToken = listenBrainzToken,
                    listenBrainzStatusLabel = listenBrainzStatusLabel,
                    listenBrainzErrorLabel = listenBrainzErrorLabel,
                    onPcHandoffEnabledChange = onPcHandoffEnabledChange,
                    onLastFmEnabledChange = onLastFmEnabledChange,
                    onStartLastFmWebAuth = onStartLastFmWebAuth,
                    onCompleteLastFmWebAuth = onCompleteLastFmWebAuth,
                    onDisconnectLastFm = onDisconnectLastFm,
                    onOpenLastFmApiAccounts = onOpenLastFmApiAccounts,
                    onListenBrainzEnabledChange = onListenBrainzEnabledChange,
                    onSaveListenBrainzToken = onSaveListenBrainzToken,
                    onDisconnectListenBrainz = onDisconnectListenBrainz,
                    onOpenConnect = onOpenConnect,
                )
                SettingsCategory.Library -> SettingsLibraryContent(
                    trackAudioInfoTagsVisible = trackAudioInfoTagsVisible,
                    onTrackAudioInfoTagsVisibleChange = onTrackAudioInfoTagsVisibleChange,
                    onOpenLibrary = onOpenLibrary,
                )
                SettingsCategory.About -> SettingsAboutContent(
                    appVersionLabel = appVersionLabel,
                    errorLogCount = errorLogCount,
                    onOpenErrorLog = onOpenErrorLog,
                )
        }
    }
}
